version: '3'
services:
  minio:
    image: bitnami/minio:latest
    networks:
      - api-gateway-network
      - fileuploader-network
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: bucket-test
    volumes:
      - data:/bitnami/minio/data
volumes:
  data:
    driver: local

networks:
  api-gateway-network:
    external: true
  fileuploader-network:
    external: true